name 'lamp'
maintainer '@axeloz'
maintainer_email 'axeloz@mabox.eu'
license 'GPLv3'
description 'Installs / configures a preconfigured LAMP server'
long_description 'Installs / configures a preconfigured LAMP server'
version '1.0'
